development:
  adapter: postgresql
  encoding: unicode
  database: front_end_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: front_end_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: front_end_production
  pool: 5
  username:
  password:
